### PR TITLE
Packaging updates

### LINKED ISSUE #166: Modernizing and extending the build backend
I've been working on creating a [conda channel ](https://anaconda.org/rydiqule/repo) for a project of mine that highly depends on ARC, so I've been [vendoring the package](https://github.com/QTC-UMD/rydiqule-vendored-conda-builds). I'm trying to extend the build to osx-arm64 and been having a devil of a time (for reasons largely unrelated to ARC itself).

During the course of this, I've noticed a number of deprecation warnings from both `pip` and `build` that probably need to be addressed. The following results from installing an editable copy of arc using pip with the verbose flag on.

```bash
            ********************************************************************************
            Usage of dash-separated 'description-file' will not be supported in future
            versions. Please use the underscore name 'description_file' instead.

            By 2024-Sep-26, you need to update your project and remove deprecated calls
            or your builds will no longer be supported.

            See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
            ********************************************************************************
```

```bash
            ********************************************************************************
            Requirements should be satisfied by a PEP 517 installer.
            If you are using pip, you can try `pip install --use-pep517`.
            ********************************************************************************
```

```bash
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
```

```bash
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
```

I'm wondering if you would be interested in going beyond addressing the deprecation warnings and overhauling the packaging/build backend for ARC to have it be a little more modern (in the ever changing python packaging seas)? Primarily moving [current PyPA guidelines](https://packaging.python.org/en/latest/tutorials/packaging-projects/) which mostly involves moving project metadata and build configuration to `pyproject.toml`.

At the same time, I'd like to also extend the build to cover the `osx-arm64` architecture so the M1 users don't have to locally compile ARC to use it. Github now has osx-arm64 runners so it should be fairly simple.

Happy to put in the work if you are interested dealing the PR.

### PR DESCRIPTION
**Pull request by dihm**
Fixes #166 

This PR modernizes the packaging for ARC, allowing to be PEP-517 compliant and fixing some other deprecations in the build process. It fully implements a `pyproject.toml` description file that contains all meta-data as well as install and setup requirements.

Note that the new build process uses isolated build environments using PyPA's `build` or via `pip`.

I've confirmed basic operation, but more thorough checks are warranted to ensure meta data hasn't been lost or package functionality is not fundamentally broken somehow.

### CODE REVIEW

**Comment by dihm** [comment]
Regarding osx-arm64 builds, since v3.4.1 ARC technically [already has them](https://pypi.org/project/ARC-Alkali-Rydberg-Calculator/3.4.1/#files) via the `universal2` package standard. This is because the `macos-latest` runner was recently updated by github to run on M1 hardware, and the default python installed by the `setup-python` action uses the `universal2` "architecture" (which includes both x64 and arm64 binaries). 

This is probably good enough, though it should be noted that scipy packages (numpy, scipy, matplotlib, etc) have chosen not to use `universal2` and instead build each architecture individually. There may or may not be a good reason behind that, but I'll have to test on an M1 mac to see if it matters.

Final question: is there a particular reason you don't distribute wheels for linux? It would be fairly easy to add to the workflows.

**Comment by dihm** [comment]
I have confirmed that the `universal2` builds work for M1 macs (in both normal python installs and conda python). I'm inclined to leave things as is in that regard.

I've also confirmed the build source tarballs are identical (up to intended changes), and the built wheels install functional packages.

**Review by nikolasibalic — APPROVED** [review]
I think we will need to keep
```
- requirements: doc/requirements.txt
````
in `.readthedocs.yaml` as these are [requirements for documentation building](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#how-to-create-reproducible-builds), which are separate from the package build requirements. But the rest looks great (thank you for your efforts!). I will merge therefore this PR, and then check and add the above line, before releasing new version.

**Comment by dihm** [comment]
That is interesting. I thought my change would install the package with pip during the docs build, pulling the requirements from the project.toml that way and reducing the amount of redundant information. 

But I didn't think too hard about it and RTD has a mind of its own when it comes to these things.

Apologies for the incomplete solution.

**Comment by nikolasibalic** [comment]
I have updated CI workflow (#168 ) so that it uses build wheels action used by scipy and numpy projects. So now we have wheels for Linux, and for Mac (and Mac ones are separated by architecture; should be better in principle).

Everything is released now as ver 3.5.0. I hope with new build system the installation will be smoother.

Thank you for your contribution @dihm !

**Pull request merged**
